version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.10.2
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI:-8080}:${PORT_WEB_UI:-8080}"
    environment:
      - SERVICES=serverless,sqs,stepfunctions,cloudformation,sts
      - DEFAULT_REGION=eu-west-1
      - DEBUG=${DEBUG:-}
      - DATA_DIR=${DATA_DIR:-}
      - PORT_WEB_UI=${PORT_WEB_UI:-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
