#
# Serverless configuration reference:
#
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#
service: event

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  handle_event:
    handler: handler.handle_event
    events:
      - sns: my-events

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # Comment out if you want to deploy to AWS instead of LocalStack
      - dev
