service: hello-http

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/{name}
          method: get

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - dev
