#
# Serverless configuration reference:
#
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#
service: hello-http

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/{name}
          method: get

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # Comment out if you want to deploy to AWS instead of LocalStack
      - dev
